### ISSUE TITLE
How to change icons folder ?

### ISSUE THREAD

**Issue by HaxorGaruda** [brokoli-mate/Suru-mate-dark-#1]
How to change color icons folder like suru-plus icons ?

**Comment by brokoli-mate** [comment]
Just use the script for suru-plus icons and use the Suru-mate-dark- name of the theme.

**Comment by HaxorGaruda** [comment]
just got error is not a valid color ... 
![suru-mate-dark-](https://user-images.githubusercontent.com/5996055/48311535-2f26c280-e56f-11e8-90e4-adceb8f4e249.png)

**Comment by brokoli-mate** [comment]
> just got error is not a valid color ...
> ![suru-mate-dark-](https://user-images.githubusercontent.com/5996055/48311535-2f26c280-e56f-11e8-90e4-adceb8f4e249.png)

I just had updated places folders to work with the latest script. Just download current version and everything should work. Thanks for mentioning this issue.

**Comment by HaxorGaruda** [comment]
thanks.. now all works perfectly..

**Comment by gusbemacbe** [comment]
Hi @brokoli-mate !

I inform that I have upgraded the icons theme yesterday and added Linux-Mint-coloured folders. I have increased from 2,2k to 4,7 icons.
